services:
  hubs:
    image: oven/bun:canary-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:${PORT:-1997}:1997
    environment:
      - HUBLISTEN=0.0.0.0:1997
    restart: always
    command: /bin/sh -c "bun i && bun update && bun index.ts"
